name: opms
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.4.0 <4.0.0'

flutter_gen:
  output: lib/utils/gen

#----------------- PACKAGES -----------------#
dependencies:
  flutter:
    sdk: flutter

  # Utility Packages
  intl: ^0.18.0
  logger: ^2.3.0
  lottie: ^3.1.2

  #  url_launcher: ^6.2.6
  smooth_page_indicator: ^1.2.0+3
  go_router: ^16.0.0
  flutter_gen: ^5.8.0
  flutter_screenutil: ^5.9.3
  measure_size_builder: ^1.0.3
  flutter_otp_text_field: ^1.2.0
  fluttertoast: ^8.2.8
  loading_animation_widget: ^1.3.0
  scroll_date_picker: ^3.8.0
  shimmer: ^3.0.0
  dotted_border: ^2.1.0
  percent_indicator: ^4.2.4
  flutter_staggered_grid_view: ^0.7.0
  cached_network_image: ^3.4.1
  flutter_staggered_animations: ^1.1.1
  dartz: ^0.10.1
  url_launcher: any
  data_table_2: ^2.6.0
  # i have updtaed this package cause it needs to be the last version for flutter 3.32
  skeletonizer: ^2.0.1

  # Icons
  iconsax: ^0.0.8
  cupertino_icons: ^1.0.6
  flutter_svg: ^2.0.10+1
  iconsax_flutter: ^1.0.0

  # State Management
  get: ^4.7.2


  carousel_slider: ^5.0.0


  # Storage
  shared_preferences: ^2.3.2


  # Api
  dio: ^5.7.0
  pretty_dio_logger: ^1.4.0


  # Firebase
  firebase_core: ^3.8.0
  firebase_messaging: ^15.1.5

  # Files

  animate_do: ^4.2.0
  collection: ^1.19.1


#----------------- ./ PACKAGES END -----------------#

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  #----------------- LOCAL ASSETS -----------------#

  assets:
    - assets/images/
    - assets/svg/
    - assets/json/

  #----------------- LOCAL FONTS -----------------#

  fonts:
    - family: Cairo
      fonts:
        - asset: assets/fonts/Cairo/Cairo-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/Cairo/Cairo-Light.ttf
          weight: 300
        - asset: assets/fonts/Cairo/Cairo-Regular.ttf
          weight: 400
        - asset: assets/fonts/Cairo/Cairo-Medium.ttf
          weight: 500
        - asset: assets/fonts/Cairo/Cairo-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Cairo/Cairo-Bold.ttf
          weight: 700
        - asset: assets/fonts/Cairo/Cairo-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/Cairo/Cairo-Black.ttf
          weight: 900


