name: opms
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.4.0 <4.0.0'

flutter_gen:
  output: lib/utils/gen

#----------------- PACKAGES -----------------#
dependencies:
  flutter:
    sdk: flutter

  # Utility Packages
  intl: ^0.18.0
  logger: ^2.3.0
  lottie: ^3.1.2

  #  url_launcher: ^6.2.6
  smooth_page_indicator: ^1.2.0+3
  go_router: ^14.3.0
  flutter_gen: ^5.8.0
  flutter_screenutil: ^5.9.3
  measure_size_builder: ^1.0.3
  flutter_otp_text_field: ^1.2.0
  fluttertoast: ^8.2.8
  loading_animation_widget: ^1.3.0
  scroll_date_picker: ^3.8.0
  shimmer: ^3.0.0
  dotted_border: ^2.1.0
  percent_indicator: ^4.2.4
  cached_network_image: ^3.4.1
  flutter_staggered_animations: ^1.1.1
  dartz: ^0.10.1
  url_launcher: any
  data_table_2: ^2.6.0

  # Icons
  iconsax: ^0.0.8
  cupertino_icons: ^1.0.6
  flutter_svg: ^2.0.10+1
  iconsax_flutter: ^1.0.0

  # State Management
  get: ^4.6.6
  get_it: ^8.0.1

  carousel_slider: ^5.0.0
  readmore: ^3.0.0
  flutter_rating_bar: ^4.0.1

  # Storage
  shared_preferences: ^2.3.2
  get_storage: ^2.1.1

  # Api
  dio: ^5.7.0
  pretty_dio_logger: ^1.4.0
  http: ^1.3.0

  # Firebase
  firebase_core: ^3.8.0
  firebase_messaging: ^15.1.5

  # Files
  image_picker: ^1.1.2
  file_picker: ^8.1.4


#----------------- ./ PACKAGES END -----------------#

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  #----------------- LOCAL ASSETS -----------------#

  assets:
    - assets/images/
    - assets/svg/
    - assets/json/

  #----------------- LOCAL FONTS -----------------#

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Black.ttf
        - asset: assets/fonts/Poppins-BlackItalic.ttf
        - asset: assets/fonts/Poppins-Bold.ttf
        - asset: assets/fonts/Poppins-BoldItalic.ttf
        - asset: assets/fonts/Poppins-ExtraBold.ttf
        - asset: assets/fonts/Poppins-ExtraBoldItalic.ttf
        - asset: assets/fonts/Poppins-ExtraLight.ttf
        - asset: assets/fonts/Poppins-ExtraLightItalic.ttf
        - asset: assets/fonts/Poppins-Italic.ttf
        - asset: assets/fonts/Poppins-Light.ttf
        - asset: assets/fonts/Poppins-LightItalic.ttf
        - asset: assets/fonts/Poppins-Medium.ttf
        - asset: assets/fonts/Poppins-MediumItalic.ttf
        - asset: assets/fonts/Poppins-Regular.ttf
        - asset: assets/fonts/Poppins-SemiBold.ttf
        - asset: assets/fonts/Poppins-SemiBoldItalic.ttf
        - asset: assets/fonts/Poppins-Thin.ttf
        - asset: assets/fonts/Poppins-ThinItalic.ttf


